### ISSUE TITLE
Exception: accountId cannot be null

### ISSUE THREAD

**Issue by nikolaimaximilian** [elucidsoft/dotnet-stellar-sdk#157]
**Describe the bug**
Getting an exception when trying to get account, see here:
`var account = server.Accounts.Account(keyPair).Result;`

This used to work and has only just stopped working. I have not updated/changed the version of the dotnet-stellar-sdk or changed the testnet-server.

**Screenshots:**
<img width="942" alt="screenshot 2019-03-01 13 00 44" src="https://user-images.githubusercontent.com/3739356/53611356-686c6680-3c22-11e9-9233-94cabe9b579b.png">
<img width="955" alt="screenshot 2019-03-01 13 01 14" src="https://user-images.githubusercontent.com/3739356/53611363-6c988400-3c22-11e9-9ce9-985494521732.png">

**See full exception here:**
System.ArgumentNullException
  HResult=0x80004003
  Message=accountId cannot be null
Parameter name: accountId
  Source=stellar-dotnetstandard-sdk
  StackTrace:
   at stellar_dotnet_sdk.responses.Signer..ctor(String accountId, Nullable`1 weight) in C:\Users\eric\Documents\GitHub\dotnetcore-stellar-sdk\stellar-dotnet-sdk\responses\AccountResponse.cs:line 147
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObjectUsingCreatorWithParameters(JsonReader reader, JsonObjectContract contract, JsonProperty containerProperty, ObjectConstructor`1 creator, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateNewObject(JsonReader reader, JsonObjectContract objectContract, JsonProperty containerMember, JsonProperty containerProperty, String id, Boolean& createdFromNonDefaultCreator)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateList(IList list, JsonReader reader, JsonArrayContract contract, JsonProperty containerProperty, String id)

**Comment by tylercmsft** [comment]
Yes, seeing this error as well today - haven't changed my code in months.  I just posted this over at stackexchange (https://stellar.stackexchange.com/questions/2260/anyone-else-seeing-an-error-with-stellar-dotnet-sdk-accountresponse-accountid) - it is happening in the constructor of the Signer object.

**Comment by Kirbyrawr** [comment]
Hi there, we changed things related to the keypair / addresses, can you try to put keyPair.AccountId ? Thanks

**Comment by Kirbyrawr** [comment]
Also you must update to the latest version because of 0.17.0 horizon changes.

**Comment by nikolaimaximilian** [comment]
Hi @Kirbyrawr and thanks for your reply. Unfortunately, I can't find an update to your SDK, currently have 2.0.6 installed. Please let me know what to do.
Cheers

**Comment by fracek** [comment]
@nikolaimaximilian Have you tried installing version `2.1.0-beta4`? You need to enable pre-release packages, version `2.0.6` is quite old.

**Comment by elucidsoft** [comment]
I'm going to release this as an official version 2.1 today and deploy the
nuget package.

**Comment by elucidsoft** [comment]
This is already resolved in the source, if you need immediate resolution you can pull the source and build it manually.

**Comment by nukec** [comment]
AccountResponse still has KeyPair property, which at the moment returns back 0 after changes. Maybe remove that property fully or put obsolete, so people can fix their code.

**Comment by elucidsoft** [comment]
Absolutely, if you want to contribute and make this change I will accept your PR. This project only gets stronger by more community participation. Otherwise, other contributors can pick up this suggestion and commit it.
