### ISSUE TITLE
CAnnot parce XDR from transuction result

### ISSUE THREAD

**Issue by NovichikhinAlexey** [elucidsoft/dotnet-stellar-sdk#180]
Version: stellar-dotnet-sdk 2.2.28

I have a transaction with creating a sell offer. From this transaction, I cannot read "TransactionResult" XDR (testnet)

https://www.stellar.org/laboratory/#xdr-viewer?input=AAAAAAAAAGQAAAAAAAAAAQAAAAAAAAADAAAAAAAAAAAAAAAAAAAAAM%2FEe4SnT3%2Fgopz3ng3SEYJcq%2FD%2B9k6K6UsSPJLpqpV3AAAAAAGV4XUAAAABTEtLMQAAAACqysdXjcCwA0NHMgy%2BBYFMm3s5N8yUziZS4Dge3zQ05QAAAAAAAAAAAcnDgAAAAAEAAAABAAAAAAAAAAAAAAAA&type=TransactionResult

You can see that in **Offer.Flag** in this transaction we **have value = 0**

But in the library code possible to have the only Flag = 1
https://github.com/elucidsoft/dotnet-stellar-sdk/blob/19c7f47caceb8b5c2ba7e134618c57fa5bd1ae75/stellar-dotnet-sdk/responses/results/OfferEntry.cs#L75

I **expect** what this XDR should be **readable without exceptions**.

Unhandled Exception: System.SystemException: Unknown OfferEntryFlags type
   at stellar_dotnet_sdk.responses.results.OfferEntry.FlagsFromXdr(Int32 flags)
   at stellar_dotnet_sdk.responses.results.OfferEntry.FromXdr(OfferEntry entry)
   at stellar_dotnet_sdk.responses.results.ManageSellOfferSuccess.FromXdr(ManageOfferSuccessResult result)
   at stellar_dotnet_sdk.responses.results.ManageSellOfferResult.FromXdr(ManageSellOfferResult result)
   at stellar_dotnet_sdk.responses.results.OperationResult.InnerOperationResultFromXdr(OperationResultTr result)
   at stellar_dotnet_sdk.responses.results.OperationResult.FromXdr(OperationResult result)
   at System.Linq.Enumerable.SelectArrayIterator`2.ToList()
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at stellar_dotnet_sdk.responses.TransactionResult.ResultsFromXdr(OperationResult[] xdrResults)
   at stellar_dotnet_sdk.responses.TransactionResult.FromXdr(TransactionResult result)
   at stellar_dotnet_sdk.responses.TransactionResult.FromXdr(String encoded)

**Comment by fracek** [comment]
I see where the problem is. We will try to have a fix out as soon as possible.
