### ISSUE TITLE
Newtonsoft.Json.JsonReaderException on operations reading

### ISSUE THREAD

**Issue by OttoVT** [elucidsoft/dotnet-stellar-sdk#284]
**Describe the bug**

When trying to get operations for ledger 140222 (https://horizon-testnet.stellar.org) I receive an unexpected exception:

Newtonsoft.Json.JsonReaderException: Could not convert string to DateTimeOffset: +131971-04-21T00:00:00Z. Path 'claimants[0].predicate.abs_before', line 143, position 53.
   at Newtonsoft.Json.JsonReader.ReadDateTimeOffsetString(String s)
   at Newtonsoft.Json.JsonReader.ReadAsDateTimeOffset()
   at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateList(IList list, JsonReader reader, JsonArrayContract contract, JsonProperty containerProperty, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Populate(JsonReader reader, Object target)
   at stellar_dotnet_sdk.responses.OperationDeserializer.ReadJson(JsonReader reader, Type objectType, OperationResponse existingValue, Boolean hasExistingValue, JsonSerializer serializer)
   at Newtonsoft.Json.JsonConverter`1.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter, JsonReader reader, Type objectType, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateList(IList list, JsonReader reader, JsonArrayContract contract, JsonProperty containerProperty, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonConverter[] converters)
   at stellar_dotnet_sdk.responses.JsonSingleton.GetInstance[T](String content)
   at stellar_dotnet_sdk.requests.ResponseHandler`1.HandleResponse(HttpResponseMessage response)
   at stellar_dotnet_sdk.requests.RequestBuilder`1.Execute[TZ](Uri uri)
   at stellar_dotnet_sdk.requests.RequestBuilderExecutePageable`2.Execute()
   at Stellar.Domain.BlocksReader.LoadAllOperationsForLedger(Int64 blockNumber) in /home/runner/work/Sirius.Integrations.Stellar/Sirius.Integrations.Stellar/src/Stellar/Domain/BlocksReader.cs:line 566
   at Stellar.Domain.BlocksReader.ReadOrDefault(Int64 blockNumber) in /home/runner/work/Sirius.Integrations.Stellar/Sirius.Integrations.Stellar/src/Stellar/Domain/BlocksReader.cs:line 65
   at Swisschain.Sirius.Sdk.Integrations.Server.GrpcServices.BlocksService.ReadNonceBlock(ReadBlockRequest request, ServerCallContext context)

**To Reproduce**
Execute the next code:
stellar-dotnet-sdk version 5.1.1

`var server = new Server("https://horizon-testnet.stellar.org");

var page = await _server.Operations.ForLedger(140222).IncludeFailed(true)
                .Limit(100)
                .Execute();
`

**Expected behavior**
Obviously, I expect to receive all operations from the ledger.

**Screenshots**
![image](https://user-images.githubusercontent.com/14955144/98347698-32a39600-2031-11eb-94da-c94be0b372b2.png)

**Desktop (please complete the following information):**
- OS: Windows 10 Pro
- Version 2004 (Build 1904ю508)

**Additional context**
stellar-dotnet-sdk version 5.1.1

**Comment by fracek** [comment]
Looks like the string `+131971-04-21T00:00:00Z` is not a valid DateTimeOffset, I will check how we can fix this.

**Comment by OttoVT** [comment]
![image](https://user-images.githubusercontent.com/14955144/98797630-492d6100-2426-11eb-8ef8-42f6f5afb427.png)

**Comment by fracek** [comment]
The problem is because .NET `DateTimeOffset` does not support dates later than 9999-12-31 (unlike Go and Java, for example). I think we will fix this by not parsing the field and leaving it as string. I will have a discussion with the other maintainers and then will push the change.

**Comment by elucidsoft** [comment]
We have decided to leave this behavior as is but will be deploying a couple of changes to make this easier to deal with in a future release.
